import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://test.pmmp-abs.com/plantec/index');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('cbi_estateb');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('pmmp123');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'sign in' }).click();
  await page.getByText('[SLDB]').click();
  await page.getByRole('link', { name: ' FFB Harvesting' }).click();
  await page.getByRole('link', { name: ' FFB Harvesting' }).click();
  await page.getByRole('link', { name: ' Add FFB Harvesting' }).click();
  await page.getByRole('button', { name: 'Please Select Estate' }).click();
  await page.locator('a').filter({ hasText: 'KAV - Punteh' }).click();
  await page.getByRole('button', { name: 'Please Select Phase' }).click();
  await page.locator('a').filter({ hasText: 'Phase 1' }).click();
  await page.getByRole('button', { name: 'Please Select Block' }).click();
  await page.locator('a').filter({ hasText: /^Block 1$/ }).click();
  await page.getByRole('button', { name: 'Please Select Planting Year' }).click();
  await page.locator('a').filter({ hasText: /^2012$/ }).click();
  await page.locator('#toggle_nav_btn').click();
  await page.getByRole('button', { name: 'Please Select Lot' }).click();
  await page.locator('a').filter({ hasText: 'Lot 1' }).click();
  await page.getByRole('button', { name: 'Nothing Selected' }).click();
  await page.locator('a').filter({ hasText: 'Loader - Punteh' }).click();
  await page.getByRole('button', { name: 'Nothing Selected' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Loader - Punteh' }).click();
  await page.locator('a').filter({ hasText: 'LS02 - Loader Sarah' }).click();
  await page.locator('a').filter({ hasText: 'LS02 - Loader Sarah' }).click();
  await page.getByRole('textbox', { name: 'Total Harvested Bunches' }).dblclick();
  await page.getByRole('textbox', { name: 'Total Harvested Bunches' }).fill('132');
  await page.getByRole('textbox', { name: 'Unripe' }).click();
  await page.getByRole('textbox', { name: 'Unripe' }).fill('021');
  await page.getByRole('textbox', { name: 'Over Ripe' }).click();
  await page.getByRole('textbox', { name: 'Over Ripe' }).fill('01');
  await page.getByRole('textbox', { name: 'Under Ripe' }).click();
  await page.getByRole('textbox', { name: 'Under Ripe' }).fill('012');
  await page.getByRole('button', { name: ' Save' }).click();
  await page.getByRole('button', { name: 'Nothing Selected' }).click();
  await page.locator('a').filter({ hasText: 'LS02 - Loader Sarah' }).click();
  await page.locator('a').filter({ hasText: 'LS04 - Witar' }).click();
  await page.getByRole('button', { name: 'Please Select Task' }).click();
  await page.locator('a').filter({ hasText: 'T01' }).click();
  await page.getByRole('button', { name: 'Please Select Platform' }).click();
  await page.locator('a').filter({ hasText: 'Platform 8' }).click();
  await page.getByRole('button', { name: ' Save' }).click();
  await page.getByRole('button', { name: 'Back to list' }).click();
});